### ISSUE TITLE
org.sonatype.aether.RepositorySystemSession Class Not Found when maven version >= 3.1.0

### ISSUE THREAD

**Issue by ScienJus** [jcabi/jcabi-aether#87]
when i used maven `3.1.1`, running plugin would be failed like:

```
java.lang.NoClassDefFoundError: Lorg/sonatype/aether/RepositorySystemSession;
        at java.lang.Class.getDeclaredFields0(Native Method)
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
        at java.lang.Class.getDeclaredFields(Class.java:1916)
        at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:661)
        at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:366)
        at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:165)
        at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:609)
        at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:565)
        at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:551)
        at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:865)
        at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:790)
        at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:278)
        at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:210)
        at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:986)
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1019)
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:982)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1032)
        at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:55)
        at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
        at org.eclipse.sisu.plexus.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:133)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:997)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1047)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:993)
        at com.google.inject.Scopes$1$1.get(Scopes.java:59)
        at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:82)
        at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:260)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:252)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:459)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:97)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: org.sonatype.aether.RepositorySystemSession
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
        ... 57 more
```

but maven `3.0.4` is ok.

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@ScienJus what plugin are you talking about?

**Comment by ScienJus** [comment]
@yegor256  my custom plugin, just want to use `Classpath`。

when maven version >= `3.1.1`， `org.sonatype.aether.RepositorySystemSession` is instead of `org.eclipse.aether.RepositorySystemSession`。so will be this error，so this will happen。

**Comment by yegor256** [comment]
@ScienJus I think we need to see your code in order to fix that problem. can you share it here? how can we reproduce the bug?

**Comment by ScienJus** [comment]
@yegor256 

just like this:

```
Collection<File> jars = new Classpath(
                    this.project,
                    this.session.getLocalRepository().getBasedir(),
                    Arrays.asList("runtime", "compile"));
```

maven will inject `RepositorySystemSession`，but when maven version <= '3.1.1'，it is `org.sonatype.aether.RepositorySystemSession` and oterwise it is `org.eclipse.aether.RepositorySystemSession`.

you need to update `pom.xml` like :

```
 <dependency>
    <groupId>org.eclipse.aether</groupId>
    <artifactId>aether-api</artifactId>
    <version>1.0.2.v20150114</version>
</dependency>
```

from 

```
<dependency>
    <groupId>org.sonatype.aether</groupId>
    <artifactId>aether-api</artifactId>
    <version>1.13.1</version>
</dependency>
```

then it will be normal in maven 3.1

**Comment by yegor256** [comment]
@ScienJus can you submit a pull request?
